# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.incomestatements_api import IncomestatementsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIncomestatementsApi(unittest.TestCase):
    """IncomestatementsApi unit test stubs"""

    def setUp(self):
        self.api = IncomestatementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_income_statement(self):
        """Test case for create_income_statement

        Creates a new income statement.  # noqa: E501
        """
        pass

    def test_create_income_statement_items(self):
        """Test case for create_income_statement_items

        Creates income statement items for an income statement.  # noqa: E501
        """
        pass

    def test_delete_income_statement(self):
        """Test case for delete_income_statement

        Deletes an existing income statement.  # noqa: E501
        """
        pass

    def test_get_income_statement(self):
        """Test case for get_income_statement

        Returns an income statement.  # noqa: E501
        """
        pass

    def test_get_income_statement_item(self):
        """Test case for get_income_statement_item

        Returns a given item for a given income statement.  # noqa: E501
        """
        pass

    def test_list_income_statement_items(self):
        """Test case for list_income_statement_items

        Returns a list of items for a given income statement.  # noqa: E501
        """
        pass

    def test_list_income_statements(self):
        """Test case for list_income_statements

        Returns a list of income statements.  # noqa: E501
        """
        pass

    def test_update_income_statement(self):
        """Test case for update_income_statement

        Updates an income statement.  # noqa: E501
        """
        pass

    def test_update_income_statement_item(self):
        """Test case for update_income_statement_item

        Updates an income statement item for a given income statement.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
