# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.named_goal_category_ref import NamedGoalCategoryRef  # noqa: E501
from swagger_client.rest import ApiException


class TestNamedGoalCategoryRef(unittest.TestCase):
    """NamedGoalCategoryRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNamedGoalCategoryRef(self):
        """Test NamedGoalCategoryRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.named_goal_category_ref.NamedGoalCategoryRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
