# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.lifecycles_api import LifecyclesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLifecyclesApi(unittest.TestCase):
    """LifecyclesApi unit test stubs"""

    def setUp(self):
        self.api = LifecyclesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_lifecycle(self):
        """Test case for get_lifecycle

        Returns a lifecycle.  # noqa: E501
        """
        pass

    def test_list_lifecycle_statuses(self):
        """Test case for list_lifecycle_statuses

        Returns a list of available lifecycle statuses  # noqa: E501
        """
        pass

    def test_list_lifecycle_transitions(self):
        """Test case for list_lifecycle_transitions

        Returns a list of transitions for a given lifecycle.  # noqa: E501
        """
        pass

    def test_list_lifecycles(self):
        """Test case for list_lifecycles

        Returns a list of lifecycles.  # noqa: E501
        """
        pass

    def test_list_plantype_lifecycles(self):
        """Test case for list_plantype_lifecycles

        Retrieves a list of lifecycles associated with the specified planType  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
