# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.needsandpriorities_api import NeedsandprioritiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNeedsandprioritiesApi(unittest.TestCase):
    """NeedsandprioritiesApi unit test stubs"""

    def setUp(self):
        self.api = NeedsandprioritiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_question(self):
        """Test case for get_question

        Retrieves the details of a question.  # noqa: E501
        """
        pass

    def test_list_questions(self):
        """Test case for list_questions

        Retrieves a list of questions associated with the current tenant. The returned list may be filtered.  # noqa: E501
        """
        pass

    def test_list_questions_answers(self):
        """Test case for list_questions_answers

        Returns a list of the answers a client has given to a given set of questions. The answers are returned in the order that the related questions should be answered.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
