# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.recommendation_proposal_template_step import RecommendationProposalTemplateStep  # noqa: E501
from swagger_client.rest import ApiException


class TestRecommendationProposalTemplateStep(unittest.TestCase):
    """RecommendationProposalTemplateStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecommendationProposalTemplateStep(self):
        """Test RecommendationProposalTemplateStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.recommendation_proposal_template_step.RecommendationProposalTemplateStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
