# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ActivityRecurrenceValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pattern': 'ActivityRecurrencePattern',
        'starts_on': 'datetime',
        'ends_on': 'datetime'
    }

    attribute_map = {
        'pattern': 'pattern',
        'starts_on': 'startsOn',
        'ends_on': 'endsOn'
    }

    def __init__(self, pattern=None, starts_on=None, ends_on=None):  # noqa: E501
        """ActivityRecurrenceValue - a model defined in Swagger"""  # noqa: E501
        self._pattern = None
        self._starts_on = None
        self._ends_on = None
        self.discriminator = None
        if pattern is not None:
            self.pattern = pattern
        if starts_on is not None:
            self.starts_on = starts_on
        if ends_on is not None:
            self.ends_on = ends_on

    @property
    def pattern(self):
        """Gets the pattern of this ActivityRecurrenceValue.  # noqa: E501


        :return: The pattern of this ActivityRecurrenceValue.  # noqa: E501
        :rtype: ActivityRecurrencePattern
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern):
        """Sets the pattern of this ActivityRecurrenceValue.


        :param pattern: The pattern of this ActivityRecurrenceValue.  # noqa: E501
        :type: ActivityRecurrencePattern
        """

        self._pattern = pattern

    @property
    def starts_on(self):
        """Gets the starts_on of this ActivityRecurrenceValue.  # noqa: E501

        Start date of task occurrence.  # noqa: E501

        :return: The starts_on of this ActivityRecurrenceValue.  # noqa: E501
        :rtype: datetime
        """
        return self._starts_on

    @starts_on.setter
    def starts_on(self, starts_on):
        """Sets the starts_on of this ActivityRecurrenceValue.

        Start date of task occurrence.  # noqa: E501

        :param starts_on: The starts_on of this ActivityRecurrenceValue.  # noqa: E501
        :type: datetime
        """

        self._starts_on = starts_on

    @property
    def ends_on(self):
        """Gets the ends_on of this ActivityRecurrenceValue.  # noqa: E501

        End date of the task  occurrence.  # noqa: E501

        :return: The ends_on of this ActivityRecurrenceValue.  # noqa: E501
        :rtype: datetime
        """
        return self._ends_on

    @ends_on.setter
    def ends_on(self, ends_on):
        """Sets the ends_on of this ActivityRecurrenceValue.

        End date of the task  occurrence.  # noqa: E501

        :param ends_on: The ends_on of this ActivityRecurrenceValue.  # noqa: E501
        :type: datetime
        """

        self._ends_on = ends_on

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActivityRecurrenceValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActivityRecurrenceValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
