# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AppUnInstalledForValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenant': 'AppRefValue',
        'user': 'AppRefValue',
        'is_uninstalled_for_all': 'bool'
    }

    attribute_map = {
        'tenant': 'tenant',
        'user': 'user',
        'is_uninstalled_for_all': 'isUninstalledForAll'
    }

    def __init__(self, tenant=None, user=None, is_uninstalled_for_all=None):  # noqa: E501
        """AppUnInstalledForValue - a model defined in Swagger"""  # noqa: E501
        self._tenant = None
        self._user = None
        self._is_uninstalled_for_all = None
        self.discriminator = None
        if tenant is not None:
            self.tenant = tenant
        if user is not None:
            self.user = user
        if is_uninstalled_for_all is not None:
            self.is_uninstalled_for_all = is_uninstalled_for_all

    @property
    def tenant(self):
        """Gets the tenant of this AppUnInstalledForValue.  # noqa: E501


        :return: The tenant of this AppUnInstalledForValue.  # noqa: E501
        :rtype: AppRefValue
        """
        return self._tenant

    @tenant.setter
    def tenant(self, tenant):
        """Sets the tenant of this AppUnInstalledForValue.


        :param tenant: The tenant of this AppUnInstalledForValue.  # noqa: E501
        :type: AppRefValue
        """

        self._tenant = tenant

    @property
    def user(self):
        """Gets the user of this AppUnInstalledForValue.  # noqa: E501


        :return: The user of this AppUnInstalledForValue.  # noqa: E501
        :rtype: AppRefValue
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AppUnInstalledForValue.


        :param user: The user of this AppUnInstalledForValue.  # noqa: E501
        :type: AppRefValue
        """

        self._user = user

    @property
    def is_uninstalled_for_all(self):
        """Gets the is_uninstalled_for_all of this AppUnInstalledForValue.  # noqa: E501


        :return: The is_uninstalled_for_all of this AppUnInstalledForValue.  # noqa: E501
        :rtype: bool
        """
        return self._is_uninstalled_for_all

    @is_uninstalled_for_all.setter
    def is_uninstalled_for_all(self, is_uninstalled_for_all):
        """Sets the is_uninstalled_for_all of this AppUnInstalledForValue.


        :param is_uninstalled_for_all: The is_uninstalled_for_all of this AppUnInstalledForValue.  # noqa: E501
        :type: bool
        """

        self._is_uninstalled_for_all = is_uninstalled_for_all

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppUnInstalledForValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppUnInstalledForValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
