# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.base_advice_template_step import BaseAdviceTemplateStep  # noqa: F401,E501

class ClientProfileTemplateStep(BaseAdviceTemplateStep):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sections': 'ClientDetailSections',
        'service_case': 'AdviceTemplateStepServiceCase',
        'show_risk_profile_capture': 'bool',
        'client_risk_profile_configuration': 'ClientRiskProfileConfiguration',
        'show_client_investment_preference_capture': 'bool',
        'client_investment_preference_configuration': 'list[ClientInvestmentPreferenceConfiguration]'
    }
    if hasattr(BaseAdviceTemplateStep, "swagger_types"):
        swagger_types.update(BaseAdviceTemplateStep.swagger_types)

    attribute_map = {
        'sections': 'sections',
        'service_case': 'serviceCase',
        'show_risk_profile_capture': 'showRiskProfileCapture',
        'client_risk_profile_configuration': 'clientRiskProfileConfiguration',
        'show_client_investment_preference_capture': 'showClientInvestmentPreferenceCapture',
        'client_investment_preference_configuration': 'clientInvestmentPreferenceConfiguration'
    }
    if hasattr(BaseAdviceTemplateStep, "attribute_map"):
        attribute_map.update(BaseAdviceTemplateStep.attribute_map)

    def __init__(self, sections=None, service_case=None, show_risk_profile_capture=None, client_risk_profile_configuration=None, show_client_investment_preference_capture=None, client_investment_preference_configuration=None, *args, **kwargs):  # noqa: E501
        """ClientProfileTemplateStep - a model defined in Swagger"""  # noqa: E501
        self._sections = None
        self._service_case = None
        self._show_risk_profile_capture = None
        self._client_risk_profile_configuration = None
        self._show_client_investment_preference_capture = None
        self._client_investment_preference_configuration = None
        self.discriminator = None
        if sections is not None:
            self.sections = sections
        if service_case is not None:
            self.service_case = service_case
        if show_risk_profile_capture is not None:
            self.show_risk_profile_capture = show_risk_profile_capture
        if client_risk_profile_configuration is not None:
            self.client_risk_profile_configuration = client_risk_profile_configuration
        if show_client_investment_preference_capture is not None:
            self.show_client_investment_preference_capture = show_client_investment_preference_capture
        if client_investment_preference_configuration is not None:
            self.client_investment_preference_configuration = client_investment_preference_configuration
        BaseAdviceTemplateStep.__init__(self, *args, **kwargs)

    @property
    def sections(self):
        """Gets the sections of this ClientProfileTemplateStep.  # noqa: E501


        :return: The sections of this ClientProfileTemplateStep.  # noqa: E501
        :rtype: ClientDetailSections
        """
        return self._sections

    @sections.setter
    def sections(self, sections):
        """Sets the sections of this ClientProfileTemplateStep.


        :param sections: The sections of this ClientProfileTemplateStep.  # noqa: E501
        :type: ClientDetailSections
        """

        self._sections = sections

    @property
    def service_case(self):
        """Gets the service_case of this ClientProfileTemplateStep.  # noqa: E501


        :return: The service_case of this ClientProfileTemplateStep.  # noqa: E501
        :rtype: AdviceTemplateStepServiceCase
        """
        return self._service_case

    @service_case.setter
    def service_case(self, service_case):
        """Sets the service_case of this ClientProfileTemplateStep.


        :param service_case: The service_case of this ClientProfileTemplateStep.  # noqa: E501
        :type: AdviceTemplateStepServiceCase
        """

        self._service_case = service_case

    @property
    def show_risk_profile_capture(self):
        """Gets the show_risk_profile_capture of this ClientProfileTemplateStep.  # noqa: E501

        Client ShowRiskProfileCapture.  # noqa: E501

        :return: The show_risk_profile_capture of this ClientProfileTemplateStep.  # noqa: E501
        :rtype: bool
        """
        return self._show_risk_profile_capture

    @show_risk_profile_capture.setter
    def show_risk_profile_capture(self, show_risk_profile_capture):
        """Sets the show_risk_profile_capture of this ClientProfileTemplateStep.

        Client ShowRiskProfileCapture.  # noqa: E501

        :param show_risk_profile_capture: The show_risk_profile_capture of this ClientProfileTemplateStep.  # noqa: E501
        :type: bool
        """

        self._show_risk_profile_capture = show_risk_profile_capture

    @property
    def client_risk_profile_configuration(self):
        """Gets the client_risk_profile_configuration of this ClientProfileTemplateStep.  # noqa: E501


        :return: The client_risk_profile_configuration of this ClientProfileTemplateStep.  # noqa: E501
        :rtype: ClientRiskProfileConfiguration
        """
        return self._client_risk_profile_configuration

    @client_risk_profile_configuration.setter
    def client_risk_profile_configuration(self, client_risk_profile_configuration):
        """Sets the client_risk_profile_configuration of this ClientProfileTemplateStep.


        :param client_risk_profile_configuration: The client_risk_profile_configuration of this ClientProfileTemplateStep.  # noqa: E501
        :type: ClientRiskProfileConfiguration
        """

        self._client_risk_profile_configuration = client_risk_profile_configuration

    @property
    def show_client_investment_preference_capture(self):
        """Gets the show_client_investment_preference_capture of this ClientProfileTemplateStep.  # noqa: E501

        Client Preference ShowPreferenceCapture.  # noqa: E501

        :return: The show_client_investment_preference_capture of this ClientProfileTemplateStep.  # noqa: E501
        :rtype: bool
        """
        return self._show_client_investment_preference_capture

    @show_client_investment_preference_capture.setter
    def show_client_investment_preference_capture(self, show_client_investment_preference_capture):
        """Sets the show_client_investment_preference_capture of this ClientProfileTemplateStep.

        Client Preference ShowPreferenceCapture.  # noqa: E501

        :param show_client_investment_preference_capture: The show_client_investment_preference_capture of this ClientProfileTemplateStep.  # noqa: E501
        :type: bool
        """

        self._show_client_investment_preference_capture = show_client_investment_preference_capture

    @property
    def client_investment_preference_configuration(self):
        """Gets the client_investment_preference_configuration of this ClientProfileTemplateStep.  # noqa: E501

        Client InvestmentPreferenceConfiguration.  # noqa: E501

        :return: The client_investment_preference_configuration of this ClientProfileTemplateStep.  # noqa: E501
        :rtype: list[ClientInvestmentPreferenceConfiguration]
        """
        return self._client_investment_preference_configuration

    @client_investment_preference_configuration.setter
    def client_investment_preference_configuration(self, client_investment_preference_configuration):
        """Sets the client_investment_preference_configuration of this ClientProfileTemplateStep.

        Client InvestmentPreferenceConfiguration.  # noqa: E501

        :param client_investment_preference_configuration: The client_investment_preference_configuration of this ClientProfileTemplateStep.  # noqa: E501
        :type: list[ClientInvestmentPreferenceConfiguration]
        """

        self._client_investment_preference_configuration = client_investment_preference_configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClientProfileTemplateStep, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientProfileTemplateStep):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
