# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClientSegmentDocument(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'is_archived': 'bool',
        'group_ref': 'GroupRef'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'is_archived': 'isArchived',
        'group_ref': 'groupRef'
    }

    def __init__(self, id=None, name=None, is_archived=None, group_ref=None):  # noqa: E501
        """ClientSegmentDocument - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._is_archived = None
        self._group_ref = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if is_archived is not None:
            self.is_archived = is_archived
        if group_ref is not None:
            self.group_ref = group_ref

    @property
    def id(self):
        """Gets the id of this ClientSegmentDocument.  # noqa: E501

        The identifier for the ClientSegment.  # noqa: E501

        :return: The id of this ClientSegmentDocument.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ClientSegmentDocument.

        The identifier for the ClientSegment.  # noqa: E501

        :param id: The id of this ClientSegmentDocument.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ClientSegmentDocument.  # noqa: E501

        The name for the ClientSegment.  # noqa: E501

        :return: The name of this ClientSegmentDocument.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClientSegmentDocument.

        The name for the ClientSegment.  # noqa: E501

        :param name: The name of this ClientSegmentDocument.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_archived(self):
        """Gets the is_archived of this ClientSegmentDocument.  # noqa: E501

        A flag indicating whether the status is Archieved or not.  # noqa: E501

        :return: The is_archived of this ClientSegmentDocument.  # noqa: E501
        :rtype: bool
        """
        return self._is_archived

    @is_archived.setter
    def is_archived(self, is_archived):
        """Sets the is_archived of this ClientSegmentDocument.

        A flag indicating whether the status is Archieved or not.  # noqa: E501

        :param is_archived: The is_archived of this ClientSegmentDocument.  # noqa: E501
        :type: bool
        """

        self._is_archived = is_archived

    @property
    def group_ref(self):
        """Gets the group_ref of this ClientSegmentDocument.  # noqa: E501


        :return: The group_ref of this ClientSegmentDocument.  # noqa: E501
        :rtype: GroupRef
        """
        return self._group_ref

    @group_ref.setter
    def group_ref(self, group_ref):
        """Sets the group_ref of this ClientSegmentDocument.


        :param group_ref: The group_ref of this ClientSegmentDocument.  # noqa: E501
        :type: GroupRef
        """

        self._group_ref = group_ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClientSegmentDocument, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientSegmentDocument):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
