# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CostProductsValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'existing': 'CostProductValue',
        'proposed': 'CostProductValue'
    }

    attribute_map = {
        'existing': 'existing',
        'proposed': 'proposed'
    }

    def __init__(self, existing=None, proposed=None):  # noqa: E501
        """CostProductsValue - a model defined in Swagger"""  # noqa: E501
        self._existing = None
        self._proposed = None
        self.discriminator = None
        if existing is not None:
            self.existing = existing
        if proposed is not None:
            self.proposed = proposed

    @property
    def existing(self):
        """Gets the existing of this CostProductsValue.  # noqa: E501


        :return: The existing of this CostProductsValue.  # noqa: E501
        :rtype: CostProductValue
        """
        return self._existing

    @existing.setter
    def existing(self, existing):
        """Sets the existing of this CostProductsValue.


        :param existing: The existing of this CostProductsValue.  # noqa: E501
        :type: CostProductValue
        """

        self._existing = existing

    @property
    def proposed(self):
        """Gets the proposed of this CostProductsValue.  # noqa: E501


        :return: The proposed of this CostProductsValue.  # noqa: E501
        :rtype: CostProductValue
        """
        return self._proposed

    @proposed.setter
    def proposed(self, proposed):
        """Sets the proposed of this CostProductsValue.


        :param proposed: The proposed of this CostProductsValue.  # noqa: E501
        :type: CostProductValue
        """

        self._proposed = proposed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CostProductsValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CostProductsValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
