# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FeeRecurring(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'frequency': 'str',
        'starts_on': 'datetime',
        'ends_on': 'datetime'
    }

    attribute_map = {
        'frequency': 'frequency',
        'starts_on': 'startsOn',
        'ends_on': 'endsOn'
    }

    def __init__(self, frequency='annually', starts_on=None, ends_on=None):  # noqa: E501
        """FeeRecurring - a model defined in Swagger"""  # noqa: E501
        self._frequency = None
        self._starts_on = None
        self._ends_on = None
        self.discriminator = None
        if frequency is not None:
            self.frequency = frequency
        if starts_on is not None:
            self.starts_on = starts_on
        if ends_on is not None:
            self.ends_on = ends_on

    @property
    def frequency(self):
        """Gets the frequency of this FeeRecurring.  # noqa: E501

        Frequency of a recurring fee  # noqa: E501

        :return: The frequency of this FeeRecurring.  # noqa: E501
        :rtype: str
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this FeeRecurring.

        Frequency of a recurring fee  # noqa: E501

        :param frequency: The frequency of this FeeRecurring.  # noqa: E501
        :type: str
        """
        allowed_values = ["Monthly", "Quarterly", "HalfYearly", "Annually"]  # noqa: E501
        if frequency not in allowed_values:
            raise ValueError(
                "Invalid value for `frequency` ({0}), must be one of {1}"  # noqa: E501
                .format(frequency, allowed_values)
            )

        self._frequency = frequency

    @property
    def starts_on(self):
        """Gets the starts_on of this FeeRecurring.  # noqa: E501

        Fee start date  # noqa: E501

        :return: The starts_on of this FeeRecurring.  # noqa: E501
        :rtype: datetime
        """
        return self._starts_on

    @starts_on.setter
    def starts_on(self, starts_on):
        """Sets the starts_on of this FeeRecurring.

        Fee start date  # noqa: E501

        :param starts_on: The starts_on of this FeeRecurring.  # noqa: E501
        :type: datetime
        """

        self._starts_on = starts_on

    @property
    def ends_on(self):
        """Gets the ends_on of this FeeRecurring.  # noqa: E501

        Fee end date  # noqa: E501

        :return: The ends_on of this FeeRecurring.  # noqa: E501
        :rtype: datetime
        """
        return self._ends_on

    @ends_on.setter
    def ends_on(self, ends_on):
        """Sets the ends_on of this FeeRecurring.

        Fee end date  # noqa: E501

        :param ends_on: The ends_on of this FeeRecurring.  # noqa: E501
        :type: datetime
        """

        self._ends_on = ends_on

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FeeRecurring, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeeRecurring):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
