# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuestionOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order': 'int',
        'is_archived': 'bool',
        'value': 'int',
        'text': 'str'
    }

    attribute_map = {
        'order': 'order',
        'is_archived': 'isArchived',
        'value': 'value',
        'text': 'text'
    }

    def __init__(self, order=None, is_archived=None, value=None, text=None):  # noqa: E501
        """QuestionOption - a model defined in Swagger"""  # noqa: E501
        self._order = None
        self._is_archived = None
        self._value = None
        self._text = None
        self.discriminator = None
        self.order = order
        if is_archived is not None:
            self.is_archived = is_archived
        if value is not None:
            self.value = value
        self.text = text

    @property
    def order(self):
        """Gets the order of this QuestionOption.  # noqa: E501

        Display order for the question answers.  # noqa: E501

        :return: The order of this QuestionOption.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this QuestionOption.

        Display order for the question answers.  # noqa: E501

        :param order: The order of this QuestionOption.  # noqa: E501
        :type: int
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")  # noqa: E501

        self._order = order

    @property
    def is_archived(self):
        """Gets the is_archived of this QuestionOption.  # noqa: E501

        Flag indicating whether the question option has been archived or not. Archived questions options are no longer used/displayed.  # noqa: E501

        :return: The is_archived of this QuestionOption.  # noqa: E501
        :rtype: bool
        """
        return self._is_archived

    @is_archived.setter
    def is_archived(self, is_archived):
        """Sets the is_archived of this QuestionOption.

        Flag indicating whether the question option has been archived or not. Archived questions options are no longer used/displayed.  # noqa: E501

        :param is_archived: The is_archived of this QuestionOption.  # noqa: E501
        :type: bool
        """

        self._is_archived = is_archived

    @property
    def value(self):
        """Gets the value of this QuestionOption.  # noqa: E501

        The unique value identifying the answer option.  # noqa: E501

        :return: The value of this QuestionOption.  # noqa: E501
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this QuestionOption.

        The unique value identifying the answer option.  # noqa: E501

        :param value: The value of this QuestionOption.  # noqa: E501
        :type: int
        """

        self._value = value

    @property
    def text(self):
        """Gets the text of this QuestionOption.  # noqa: E501

        The text of the answer option.  # noqa: E501

        :return: The text of this QuestionOption.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this QuestionOption.

        The text of the answer option.  # noqa: E501

        :param text: The text of this QuestionOption.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuestionOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuestionOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
