# coding: utf-8

"""
    public-v2-prd-gb-01

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2016-08-19T00:00:00Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskActivityCompletion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'percentage': 'float',
        'completed_by': 'NamedUserReference',
        'completed_at': 'datetime',
        'outcome': 'NamedActivityOutcomeReference'
    }

    attribute_map = {
        'percentage': 'percentage',
        'completed_by': 'completedBy',
        'completed_at': 'completedAt',
        'outcome': 'outcome'
    }

    def __init__(self, percentage=0.0, completed_by=None, completed_at=None, outcome=None):  # noqa: E501
        """TaskActivityCompletion - a model defined in Swagger"""  # noqa: E501
        self._percentage = None
        self._completed_by = None
        self._completed_at = None
        self._outcome = None
        self.discriminator = None
        if percentage is not None:
            self.percentage = percentage
        if completed_by is not None:
            self.completed_by = completed_by
        if completed_at is not None:
            self.completed_at = completed_at
        if outcome is not None:
            self.outcome = outcome

    @property
    def percentage(self):
        """Gets the percentage of this TaskActivityCompletion.  # noqa: E501

        The percentage of the task that has been completed.  # noqa: E501

        :return: The percentage of this TaskActivityCompletion.  # noqa: E501
        :rtype: float
        """
        return self._percentage

    @percentage.setter
    def percentage(self, percentage):
        """Sets the percentage of this TaskActivityCompletion.

        The percentage of the task that has been completed.  # noqa: E501

        :param percentage: The percentage of this TaskActivityCompletion.  # noqa: E501
        :type: float
        """

        self._percentage = percentage

    @property
    def completed_by(self):
        """Gets the completed_by of this TaskActivityCompletion.  # noqa: E501


        :return: The completed_by of this TaskActivityCompletion.  # noqa: E501
        :rtype: NamedUserReference
        """
        return self._completed_by

    @completed_by.setter
    def completed_by(self, completed_by):
        """Sets the completed_by of this TaskActivityCompletion.


        :param completed_by: The completed_by of this TaskActivityCompletion.  # noqa: E501
        :type: NamedUserReference
        """

        self._completed_by = completed_by

    @property
    def completed_at(self):
        """Gets the completed_at of this TaskActivityCompletion.  # noqa: E501

        The date the task was completed.  # noqa: E501

        :return: The completed_at of this TaskActivityCompletion.  # noqa: E501
        :rtype: datetime
        """
        return self._completed_at

    @completed_at.setter
    def completed_at(self, completed_at):
        """Sets the completed_at of this TaskActivityCompletion.

        The date the task was completed.  # noqa: E501

        :param completed_at: The completed_at of this TaskActivityCompletion.  # noqa: E501
        :type: datetime
        """

        self._completed_at = completed_at

    @property
    def outcome(self):
        """Gets the outcome of this TaskActivityCompletion.  # noqa: E501


        :return: The outcome of this TaskActivityCompletion.  # noqa: E501
        :rtype: NamedActivityOutcomeReference
        """
        return self._outcome

    @outcome.setter
    def outcome(self, outcome):
        """Sets the outcome of this TaskActivityCompletion.


        :param outcome: The outcome of this TaskActivityCompletion.  # noqa: E501
        :type: NamedActivityOutcomeReference
        """

        self._outcome = outcome

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskActivityCompletion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskActivityCompletion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
